---
title: "join_data_finalproject"
author: 'IRENE MARTINEZ MORATA (UNI: im2557)'
date: "11/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("/Users/irene/Desktop/DATA SCIENCE/p8105_finalproject")

library(tidyverse)
library(readr)
library(ggplot2)
library(lubridate)
library(ggridges)
library(ggpubr)
library(purrr)


getwd()
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",

  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}

zip_mod <- read_csv("raw_data/ZCTA-to-MODZCTA.csv") %>% 
  rename(zip = ZCTA)

school <- read_csv("shsat_data.csv") 

covid_test <- read_csv("raw_data/tests-by-zcta.csv")

covid_deathrate <- read_csv("deathrate_byzcta_clean.csv")

school_data <- full_join(zip_mod, school, by = "zip") %>% 
  select(-`...1`) %>% 
  janitor::clean_names()

school_covidtest <- full_join(school_data, covid_test, by = "modzcta") %>% 
  janitor::clean_names()

school_covidtest_death <- full_join(school_covidtest, covid_deathrate, by = "modzcta") %>% 
  janitor::clean_names() %>% 
  rename_with(~ gsub('x', '', .x)) 

write_csv(school_covidtest_death, "project_df.csv")

```

