---
title: "Map"
author: 'IRENE MARTINEZ MORATA (UNI: im2557)'
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(Hmisc)     
library(dplyr)
library(openxlsx)
library(readr)
library(spdep)
library(maptools)
library(rgdal)
library(spatialreg)
library(spgwr)


getwd()
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",

  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r }
library(raster)
# read data    
map <- shapefile("shapefiles/school_map.shp") %>% 
  unique(modzcta_1)

project_df <- read_csv("project_df.csv") %>% 
  mutate(modzcta_1 = as.numeric(modzcta)) %>% 
  unique(modzcta_1)

map_df <- merge(map, project_df, by = 'modzcta_1', duplicateGeoms = TRUE)

#save it into a shapefile
working <- getwd()
writeOGR(map_df, 
         dsn = working, 
         layer= "map_df",
         driver="ESRI Shapefile")

```

#Do GWR analysis by MODZCTA

```{r}
####----- 8 GWR ####
working <- getwd()
#Read in the data and create subsets for every R/E group and metal with no NAs
#we fist remove the NAs from the selected variable
HIS <- readOGR(dsn = working, layer ="map_df")
HISas1 <- HIS[!is.na(HIS$logAs) ,]
HISas1 <- na.omit(HISas1)
#we print the clean shapefile and save it
writeOGR(HISas1, 
         dsn = working, 
         layer= "HISas",
         driver="ESRI Shapefile",overwrite_layer = TRUE)

#create the adaptative bandwidth
bwG1 <- gwr.sel(logAs ~ jHspn + jMdn_ + jHgh_ + jdnst + GWP10 , 
                data= HISas1, 
                gweight=gwr.Gauss, 
                verbose=TRUE, 
                adapt = TRUE)
#run GWR with adaptative bandwith and with se and residuals, and global R2
gwr.HISas = gwr(logAs ~ jHspn + jMdn_ + jHgh_ + jdnst + GWP10 , 
                data= HISas1, 
                adapt=bwG1,
                hatmatrix=TRUE,
                se.fit=TRUE)
#double check the data
gwr.HISas
#save the estimates into a shapefile to plot in QGIS
names (gwr.HISas$SDF)
writeOGR(gwr.HISas$SDF, 
         dsn = working, 
         layer= "HISas_GWR",
         driver="ESRI Shapefile")

```

